# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-21 18:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shows_app', '0006_remove_shows_rating'),
        ('l_r_app', '0002_users_show'),
    ]

    operations = [
        migrations.CreateModel(
            name='ratings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('showid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='shows_app.shows')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='l_r_app.users')),
            ],
        ),
    ]
