# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-20 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shows',
            name='video',
            field=models.CharField(default='https', max_length=1250),
            preserve_default=False,
        ),
    ]
