# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-20 22:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows_app', '0002_shows_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shows',
            name='video',
            field=models.URLField(max_length=1250),
        ),
    ]
