# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-21 00:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows_app', '0004_shows_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='shows',
            name='theme',
            field=models.CharField(default='none', max_length=45),
            preserve_default=False,
        ),
    ]
