# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-21 18:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows_app', '0005_shows_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shows',
            name='rating',
        ),
    ]
