# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-21 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows_app', '0006_remove_shows_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='shows',
            name='rate',
            field=models.IntegerField(default=0),
        ),
    ]
