# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-21 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows_app', '0007_shows_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shows',
            name='air_date',
            field=models.DateField(null=True),
        ),
    ]
