# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-21 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows_app', '0008_auto_20181121_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shows',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
